import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'wouter';
import { AlertTriangle, CalendarClock, CheckCircle2, ChevronRight, CircleDollarSign, Play, Repeat2, ShieldCheck, Sparkles } from 'lucide-react';
import { customFetch } from '@workspace/api-client-react/custom-fetch';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Switch } from '@/components/ui/switch';
import { formatCurrency } from '@/lib/utils';

type CommandData = { tasks: Array<{ id: string; priority: string; title: string; detail: string; href: string }>; balances: Array<{ id: number; name: string; balance: number }>; upcomingBills: Array<{ id: number; title: string; dueDate: string; amount?: string }>; activeSubscriptions: number; unreadNotifications: number; allClear: boolean };
type CashFlow = { openingBalance: number; events: Array<{ date: string; title: string; amount: number; projectedBalance: number; warning: boolean }>; lowestBalance: number; hasShortfall: boolean };
type Subscriptions = { subscriptions: Array<{ id: number; merchant: string; amount: string; frequency: string; nextChargeDate?: string; status: string; cancelUrl?: string }>; detected: Array<{ merchant: string; average: string; occurrences: number; lastCharge: string }> };

export default function CommandCenter() {
  const client = useQueryClient();
  const [sandbox, setSandbox] = useState(() => sessionStorage.getItem('finance-sandbox') === 'true');
  const command = useQuery({ queryKey: ['command-center'], queryFn: () => customFetch<CommandData>('/api/command-center', { responseType: 'json' }) });
  const cash = useQuery({ queryKey: ['cash-flow'], queryFn: () => customFetch<CashFlow>('/api/cash-flow?days=30', { responseType: 'json' }) });
  const subs = useQuery({ queryKey: ['subscriptions'], queryFn: () => customFetch<Subscriptions>('/api/subscriptions', { responseType: 'json' }) });
  const saveSubscription = useMutation({ mutationFn: (item: { merchant: string; average: string }) => customFetch('/api/subscriptions', { method: 'POST', responseType: 'json', body: JSON.stringify({ merchant: item.merchant, amount: Number(item.average), frequency: 'monthly', source: 'detected' }) }), onSuccess: () => client.invalidateQueries({ queryKey: ['subscriptions'] }) });
  const cancelSubscription = useMutation({ mutationFn: (id: number) => customFetch(`/api/subscriptions/${id}`, { method: 'PATCH', responseType: 'json', body: JSON.stringify({ status: 'cancelled' }) }), onSuccess: () => client.invalidateQueries({ queryKey: ['subscriptions'] }) });
  const onboarding = useMemo(() => [
    { label: 'Create your financial accounts', done: (command.data?.balances.length ?? 0) > 0, href: '/accounts' },
    { label: 'Record or import transactions', done: false, href: '/transactions' },
    { label: 'Set your first spending budget', done: false, href: '/budgets' },
    { label: 'Create an emergency goal', done: false, href: '/goals' },
  ], [command.data]);
  const progress = onboarding.filter(item => item.done).length / onboarding.length * 100;
  const setDemo = (value: boolean) => { setSandbox(value); sessionStorage.setItem('finance-sandbox', String(value)); };
  return <div className="space-y-7 pb-12">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Today</p><h1 className="mt-1 text-3xl font-bold">Financial command centre</h1><p className="mt-1 text-sm text-muted-foreground">The decisions that matter now, ordered by urgency.</p></div><div className="flex items-center gap-3 rounded-xl border bg-card px-4 py-2.5"><Play className="h-4 w-4 text-primary"/><div><p className="text-sm font-medium">Sandbox mode</p><p className="text-[11px] text-muted-foreground">Try scenarios without changing data</p></div><Switch checked={sandbox} onCheckedChange={setDemo}/></div></header>
    {sandbox && <div className="rounded-2xl border border-primary/30 bg-primary/10 p-4 text-sm"><strong>Safe simulation is active.</strong> Calculators and previews remain available, while saved financial records are protected.</div>}
    <div className="grid gap-4 sm:grid-cols-3"><Metric icon={CircleDollarSign} label="Accounts tracked" value={String(command.data?.balances.length ?? 0)} /><Metric icon={Repeat2} label="Active subscriptions" value={String(command.data?.activeSubscriptions ?? 0)} /><Metric icon={CalendarClock} label="30-day lowest balance" value={formatCurrency(cash.data?.lowestBalance ?? 0)} warn={cash.data?.hasShortfall} /></div>
    <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><div className="glass-card rounded-2xl p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Action queue</h2><p className="text-xs text-muted-foreground">Generated from bills, budgets, and account balances.</p></div><Sparkles className="h-5 w-5 text-primary"/></div><div className="mt-4 space-y-2">{command.data?.allClear && <Empty icon={CheckCircle2} title="You are all clear" text="No urgent financial actions were detected."/>}{command.data?.tasks.map(task => <Link key={task.id} href={task.href} className="flex items-center gap-3 rounded-xl border bg-background/40 p-3 transition hover:border-primary/40"><div className={`h-2.5 w-2.5 rounded-full ${task.priority === 'urgent' ? 'bg-red-500' : 'bg-amber-400'}`}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{task.title}</p><p className="truncate text-xs text-muted-foreground">{task.detail}</p></div><ChevronRight className="h-4 w-4 text-muted-foreground"/></Link>)}</div></div>
      <div className="glass-card rounded-2xl p-5"><h2 className="text-lg font-semibold">Getting started</h2><p className="text-xs text-muted-foreground">A guided foundation for reliable insights.</p><Progress className="mt-4" value={progress}/><p className="mt-2 text-xs text-muted-foreground">{Math.round(progress)}% complete</p><div className="mt-4 space-y-2">{onboarding.map(item => <Link href={item.href} key={item.label} className="flex items-center gap-2 rounded-lg p-2 text-sm hover:bg-white/5">{item.done ? <CheckCircle2 className="h-4 w-4 text-primary"/> : <div className="h-4 w-4 rounded-full border"/>}<span className="flex-1">{item.label}</span><ChevronRight className="h-4 w-4 text-muted-foreground"/></Link>)}</div></div></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="glass-card rounded-2xl p-5"><h2 className="text-lg font-semibold">Cash-flow runway</h2><p className="text-xs text-muted-foreground">Scheduled bills and projected balances for the next 30 days.</p><div className="mt-4 space-y-2">{cash.data?.events.length ? cash.data.events.slice(0, 8).map(event => <div key={`${event.date}-${event.title}`} className="grid grid-cols-[5.5rem_1fr_auto] items-center gap-3 rounded-xl bg-muted/40 p-3 text-sm"><span className="text-xs text-muted-foreground">{event.date}</span><span className="truncate">{event.title}</span><span className={`font-mono ${event.warning ? 'text-red-400' : ''}`}>{formatCurrency(event.projectedBalance)}</span></div>) : <Empty icon={ShieldCheck} title="No scheduled outflows" text="Add bill reminders to see your future cash position."/>}</div></div>
      <div className="glass-card rounded-2xl p-5"><h2 className="text-lg font-semibold">Subscription watch</h2><p className="text-xs text-muted-foreground">Saved services and recurring charges detected from ledger patterns.</p><div className="mt-4 space-y-2">{subs.data?.subscriptions.slice(0, 5).map(item => <div key={item.id} className="flex items-center gap-3 rounded-xl bg-muted/40 p-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.merchant}</p><p className="text-xs text-muted-foreground">{item.frequency}{item.nextChargeDate ? ` · ${item.nextChargeDate}` : ''}</p></div><span className="font-mono text-sm">{formatCurrency(Number(item.amount))}</span><Button size="sm" variant="ghost" onClick={() => cancelSubscription.mutate(item.id)}>Cancel</Button></div>)}{subs.data?.detected.slice(0, 3).map(item => <div key={item.merchant} className="flex items-center gap-3 rounded-xl border border-dashed border-primary/30 p-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.merchant}</p><p className="text-xs text-primary">Possible subscription · {item.occurrences} charges</p></div><span className="font-mono text-sm">≈{formatCurrency(Number(item.average))}</span><Button size="sm" variant="outline" onClick={() => saveSubscription.mutate(item)}>Track</Button></div>)}</div></div></section>
  </div>;
}
function Metric({ icon: Icon, label, value, warn }: { icon: typeof CircleDollarSign; label: string; value: string; warn?: boolean }) { return <div className="glass-card rounded-2xl p-5"><Icon className={`h-5 w-5 ${warn ? 'text-red-400' : 'text-primary'}`}/><p className="mt-4 text-xs text-muted-foreground">{label}</p><p className="mt-1 font-mono text-2xl font-bold">{value}</p></div>; }
function Empty({ icon: Icon, title, text }: { icon: typeof ShieldCheck; title: string; text: string }) { return <div className="py-8 text-center"><Icon className="mx-auto h-8 w-8 text-primary"/><p className="mt-2 font-medium">{title}</p><p className="text-xs text-muted-foreground">{text}</p></div>; }
