import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, FileCheck2, ReceiptText, Scale, Users } from 'lucide-react';
import { customFetch } from '@workspace/api-client-react/custom-fetch';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Progress } from '@/components/ui/progress';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { formatCurrency } from '@/lib/utils';

export default function Organize() {
  const client = useQueryClient(); const year = new Date().getFullYear(); const month = new Date().toISOString().slice(0, 7);
  const tax = useQuery({ queryKey: ['tax', year], queryFn: () => customFetch<any>(`/api/tax?year=${year}`, { responseType: 'json' }) });
  const transactions = useQuery({ queryKey: ['tax-transactions'], queryFn: () => customFetch<any>('/api/transactions?type=expense&limit=100', { responseType: 'json' }) });
  const receipts = useQuery({ queryKey: ['receipts'], queryFn: () => customFetch<any[]>('/api/receipts', { responseType: 'json' }) });
  const reviews = useQuery({ queryKey: ['reviews'], queryFn: () => customFetch<any[]>('/api/reviews', { responseType: 'json' }) });
  const households = useQuery({ queryKey: ['households'], queryFn: () => customFetch<any[]>('/api/households', { responseType: 'json' }) });
  const approvals = useQuery({ queryKey: ['approvals'], queryFn: () => customFetch<any[]>('/api/household-approvals', { responseType: 'json' }) });
  const [receipt, setReceipt] = useState({ filename: '', merchant: '', amount: '', purchasedAt: '' }); const [review, setReview] = useState({ step: 1, wins: '', concerns: '', nextAction: '' }); const [approval, setApproval] = useState({ householdId: '', title: '', amount: '' }); const [taxForm, setTaxForm] = useState({ transactionId: '', classification: 'Business expense', deductiblePercent: '100' });
  const addReceipt = useMutation({ mutationFn: () => customFetch('/api/receipts', { method: 'POST', responseType: 'json', body: JSON.stringify(receipt) }), onSuccess: () => { client.invalidateQueries({ queryKey: ['receipts'] }); setReceipt({ filename: '', merchant: '', amount: '', purchasedAt: '' }); } });
  const saveReview = useMutation({ mutationFn: (complete: boolean) => customFetch(`/api/reviews/${month}`, { method: 'PUT', responseType: 'json', body: JSON.stringify({ step: review.step, status: complete ? 'completed' : 'in_progress', answers: { wins: review.wins, concerns: review.concerns, nextAction: review.nextAction } }) }), onSuccess: () => client.invalidateQueries({ queryKey: ['reviews'] }) });
  const requestApproval = useMutation({ mutationFn: () => customFetch('/api/household-approvals', { method: 'POST', responseType: 'json', body: JSON.stringify(approval) }), onSuccess: () => { client.invalidateQueries({ queryKey: ['approvals'] }); setApproval({ householdId: '', title: '', amount: '' }); } });
  const decide = useMutation({ mutationFn: ({ id, status }: { id: number; status: string }) => customFetch(`/api/household-approvals/${id}`, { method: 'PATCH', responseType: 'json', body: JSON.stringify({ status }) }), onSuccess: () => client.invalidateQueries({ queryKey: ['approvals'] }) });
  const tagTax = useMutation({ mutationFn: () => customFetch('/api/tax', { method: 'POST', responseType: 'json', body: JSON.stringify({ ...taxForm, taxYear: year }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ['tax'] }); setTaxForm({ transactionId: '', classification: 'Business expense', deductiblePercent: '100' }); } });
  return <div className="space-y-7 pb-12"><header><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Organize</p><h1 className="mt-1 text-3xl font-bold">Financial workspace</h1><p className="mt-1 text-sm text-muted-foreground">Keep evidence, tax decisions, monthly reviews, and household approvals together.</p></header>
    <Tabs defaultValue="tax"><TabsList className="grid h-auto grid-cols-2 sm:grid-cols-4"><TabsTrigger value="tax">Tax centre</TabsTrigger><TabsTrigger value="receipts">Receipts</TabsTrigger><TabsTrigger value="review">Monthly review</TabsTrigger><TabsTrigger value="household">Household</TabsTrigger></TabsList>
      <TabsContent value="tax" className="mt-5 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Summary icon={Scale} label={`${year} deductible total`} value={formatCurrency(tax.data?.deductibleTotal ?? 0)}/><Summary icon={FileCheck2} label="Tagged transactions" value={String(tax.data?.rows?.length ?? 0)}/></div><form className="glass-card grid gap-3 rounded-2xl p-5 sm:grid-cols-[1.5fr_1fr_.6fr_auto] sm:items-end" onSubmit={e => { e.preventDefault(); tagTax.mutate(); }}><div><Label>Expense transaction</Label><Select value={taxForm.transactionId} onValueChange={transactionId => setTaxForm({ ...taxForm, transactionId })}><SelectTrigger className="mt-1"><SelectValue placeholder="Choose an expense"/></SelectTrigger><SelectContent>{(transactions.data?.data ?? transactions.data ?? []).map((item: any) => <SelectItem key={item.id} value={String(item.id)}>{item.date} · {item.description || item.merchant} · {formatCurrency(Number(item.amount))}</SelectItem>)}</SelectContent></Select></div><div><Label>Classification</Label><Input className="mt-1" value={taxForm.classification} onChange={e => setTaxForm({ ...taxForm, classification: e.target.value })}/></div><div><Label>Deductible %</Label><Input className="mt-1" type="number" min="0" max="100" value={taxForm.deductiblePercent} onChange={e => setTaxForm({ ...taxForm, deductiblePercent: e.target.value })}/></div><Button disabled={!taxForm.transactionId}>Tag expense</Button></form><div className="glass-card overflow-hidden rounded-2xl"><div className="border-b p-5"><h2 className="font-semibold">Tax-ready activity</h2><p className="text-xs text-muted-foreground">Classification is user-controlled and should be reviewed with a qualified tax professional.</p></div><div className="divide-y">{tax.data?.rows?.map((row: any) => <div key={row.tag.id} className="grid gap-2 p-4 sm:grid-cols-[1fr_auto_auto]"><div><p className="font-medium">{row.transaction.description || row.transaction.merchant}</p><p className="text-xs text-muted-foreground">{row.tag.classification} · {row.tag.deductiblePercent}% deductible</p></div><span className="font-mono">{formatCurrency(Number(row.transaction.amount))}</span><span className="text-xs text-muted-foreground">{row.transaction.date}</span></div>)}{!tax.data?.rows?.length && <Empty text="Tag an expense above to build the tax ledger."/>}</div></div></TabsContent>
      <TabsContent value="receipts" className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><form className="glass-card space-y-4 rounded-2xl p-5" onSubmit={e => { e.preventDefault(); addReceipt.mutate(); }}><div><ReceiptText className="h-6 w-6 text-primary"/><h2 className="mt-3 font-semibold">Add receipt for review</h2><p className="text-xs text-muted-foreground">Record extracted fields now; encrypted object storage/OCR can populate the same workflow when configured.</p></div>{Object.entries(receipt).map(([key, value]) => <div key={key}><Label className="capitalize">{key.replace(/([A-Z])/g, ' $1')}</Label><Input className="mt-1" type={key === 'amount' ? 'number' : key === 'purchasedAt' ? 'date' : 'text'} value={value} onChange={e => setReceipt({ ...receipt, [key]: e.target.value })}/></div>)}<Button className="w-full">Add to receipt vault</Button></form><div className="space-y-3">{receipts.data?.map(item => <div key={item.id} className="glass-card flex items-center gap-4 rounded-xl p-4"><div className="rounded-xl bg-primary/10 p-2"><ReceiptText className="h-5 w-5 text-primary"/></div><div className="min-w-0 flex-1"><p className="truncate font-medium">{item.filename}</p><p className="text-xs text-muted-foreground">{item.merchant || 'Merchant pending'} · {item.ocrStatus.replace('_', ' ')}</p></div><p className="font-mono text-sm">{item.amount ? formatCurrency(Number(item.amount)) : '—'}</p></div>)}{!receipts.data?.length && <Empty text="Your matched receipts and OCR review queue will appear here."/>}</div></TabsContent>
      <TabsContent value="review" className="mt-5"><div className="glass-card mx-auto max-w-3xl rounded-2xl p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">{month} guided review</h2><p className="text-sm text-muted-foreground">Reflect, decide, and finish with one concrete action.</p></div><span className="text-sm text-primary">Step {review.step} of 3</span></div><Progress className="mt-4" value={review.step / 3 * 100}/><div className="mt-6">{review.step === 1 && <Field label="What went well financially this month?" value={review.wins} onChange={wins => setReview({ ...review, wins })}/>} {review.step === 2 && <Field label="What needs attention or felt difficult?" value={review.concerns} onChange={concerns => setReview({ ...review, concerns })}/>} {review.step === 3 && <Field label="What is the single most valuable next action?" value={review.nextAction} onChange={nextAction => setReview({ ...review, nextAction })}/>}</div><div className="mt-5 flex justify-between"><Button variant="outline" disabled={review.step === 1} onClick={() => setReview({ ...review, step: review.step - 1 })}>Previous</Button>{review.step < 3 ? <Button onClick={() => { saveReview.mutate(false); setReview({ ...review, step: review.step + 1 }); }}>Save and continue</Button> : <Button onClick={() => saveReview.mutate(true)}><Check className="mr-2 h-4 w-4"/>Complete review</Button>}</div></div></TabsContent>
      <TabsContent value="household" className="mt-5 grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><form className="glass-card space-y-4 rounded-2xl p-5" onSubmit={e => { e.preventDefault(); requestApproval.mutate(); }}><Users className="h-6 w-6 text-primary"/><h2 className="font-semibold">Request approval</h2><div><Label>Household</Label><Select value={approval.householdId} onValueChange={householdId => setApproval({ ...approval, householdId })}><SelectTrigger className="mt-1"><SelectValue placeholder="Choose household"/></SelectTrigger><SelectContent>{households.data?.map((item: any) => <SelectItem key={item.household.id} value={String(item.household.id)}>{item.household.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Request</Label><Input className="mt-1" value={approval.title} onChange={e => setApproval({ ...approval, title: e.target.value })}/></div><div><Label>Amount</Label><Input className="mt-1" type="number" value={approval.amount} onChange={e => setApproval({ ...approval, amount: e.target.value })}/></div><Button className="w-full" disabled={!approval.householdId || !approval.title}>Submit request</Button></form><div className="space-y-3">{approvals.data?.map(item => <div key={item.id} className="glass-card rounded-xl p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{item.title}</p><p className="text-xs capitalize text-muted-foreground">{item.type} · {item.status}</p></div>{item.amount && <p className="font-mono">{formatCurrency(Number(item.amount))}</p>}</div>{item.status === 'pending' && <div className="mt-3 flex gap-2"><Button size="sm" onClick={() => decide.mutate({ id: item.id, status: 'approved' })}>Approve</Button><Button size="sm" variant="outline" onClick={() => decide.mutate({ id: item.id, status: 'rejected' })}>Reject</Button></div>}</div>)}{!approvals.data?.length && <Empty text="Shared budget and spending approvals will appear here."/>}</div></TabsContent>
    </Tabs></div>;
}
function Summary({ icon: Icon, label, value }: { icon: typeof Scale; label: string; value: string }) { return <div className="glass-card rounded-2xl p-5"><Icon className="h-5 w-5 text-primary"/><p className="mt-4 text-xs text-muted-foreground">{label}</p><p className="mt-1 font-mono text-2xl font-bold">{value}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="glass-card rounded-2xl p-10 text-center text-sm text-muted-foreground">{text}</div>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div><Label>{label}</Label><Textarea className="mt-2 min-h-32" value={value} onChange={e => onChange(e.target.value)} placeholder="Write a short, honest answer…"/></div>; }
