import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BellRing, GripVertical, LayoutGrid, Save } from 'lucide-react';
import { customFetch } from '@workspace/api-client-react/custom-fetch';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import PagePurpose from '@/components/PagePurpose';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

const widgetCatalog = [
  ['net-worth', 'Net worth'], ['cash-flow', 'Cash-flow runway'], ['budgets', 'Budget health'], ['subscriptions', 'Subscriptions'],
  ['emergency', 'Emergency fund'], ['credit', 'Credit utilization'], ['investments', 'Asset allocation'], ['tasks', 'Action queue'],
];
export default function Studio() {
  const client = useQueryClient(); const layouts = useQuery({ queryKey: ['layouts'], queryFn: () => customFetch<any[]>('/api/dashboard-layouts', { responseType: 'json' }) });
  const notificationData = useQuery({ queryKey: ['notifications'], queryFn: () => customFetch<any>('/api/notifications', { responseType: 'json' }) });
  const [name, setName] = useState('My dashboard'); const [widgets, setWidgets] = useState<string[]>(['net-worth', 'cash-flow', 'budgets', 'tasks']);
  const [prefs, setPrefs] = useState<any>({ lowBalance: true, bills: true, budgets: true, subscriptions: true, weeklyDigest: true, lowBalanceThreshold: 500 });
  const saveLayout = useMutation({ mutationFn: () => customFetch('/api/dashboard-layouts', { method: 'POST', responseType: 'json', body: JSON.stringify({ name, widgets, isDefault: true }) }), onSuccess: () => client.invalidateQueries({ queryKey: ['layouts'] }) });
  const savePrefs = useMutation({ mutationFn: () => customFetch('/api/notification-preferences', { method: 'PUT', responseType: 'json', body: JSON.stringify(prefs) }), onSuccess: () => client.invalidateQueries({ queryKey: ['notifications'] }) });
  const toggleWidget = (id: string) => setWidgets(items => items.includes(id) ? items.filter(item => item !== id) : [...items, id]);
  return <div className="space-y-7 pb-12"><header><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Personalize</p><h1 className="mt-1 text-3xl font-bold">Experience studio</h1><p className="mt-1 text-sm text-muted-foreground">Choose what appears first and control when Finance Intelli asks for attention.</p></header><PagePurpose items={[{ icon: LayoutGrid, title: 'Shape your dashboard', description: 'Choose which information deserves priority.' }, { icon: GripVertical, title: 'Arrange your workflow', description: 'Put the most useful modules within easy reach.' }, { icon: Save, title: 'Save your preferences', description: 'Keep a consistent workspace for future visits.' }, { icon: BellRing, title: 'Control attention', description: 'Decide which financial events should notify you.' }]} />
    <Tabs defaultValue="dashboard"><TabsList><TabsTrigger value="dashboard">Dashboard builder</TabsTrigger><TabsTrigger value="notifications">Notifications</TabsTrigger></TabsList>
      <TabsContent value="dashboard" className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="glass-card rounded-2xl p-5"><LayoutGrid className="h-6 w-6 text-primary"/><h2 className="mt-3 font-semibold">Widget library</h2><p className="text-xs text-muted-foreground">Select only the information that supports your decisions.</p><div className="mt-5 space-y-2">{widgetCatalog.map(([id, label]) => <label key={id} className="flex cursor-pointer items-center gap-3 rounded-xl border p-3 hover:border-primary/40"><Switch checked={widgets.includes(id)} onCheckedChange={() => toggleWidget(id)}/><span className="flex-1 text-sm">{label}</span></label>)}</div></div><div className="space-y-4"><div className="glass-card rounded-2xl p-5"><Label>Dashboard name</Label><div className="mt-2 flex gap-2"><Input value={name} onChange={e => setName(e.target.value)}/><Button onClick={() => saveLayout.mutate()} disabled={!name || !widgets.length}><Save className="mr-2 h-4 w-4"/>Save</Button></div></div><div className="glass-card rounded-2xl p-5"><h2 className="font-semibold">Preview order</h2><p className="text-xs text-muted-foreground">The saved widget order is respected by dashboard-capable clients.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{widgets.map((id, index) => <div key={id} className="flex items-center gap-3 rounded-xl border bg-background/40 p-4"><GripVertical className="h-4 w-4 text-muted-foreground"/><span className="flex-1 text-sm font-medium">{widgetCatalog.find(item => item[0] === id)?.[1]}</span><span className="text-xs text-muted-foreground">{index + 1}</span></div>)}</div></div>{layouts.data?.length ? <p className="text-xs text-muted-foreground">Saved layouts: {layouts.data.map(item => item.name).join(', ')}</p> : null}</div></TabsContent>
      <TabsContent value="notifications" className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="glass-card rounded-2xl p-5"><BellRing className="h-6 w-6 text-primary"/><h2 className="mt-3 font-semibold">Alert preferences</h2><div className="mt-5 space-y-2">{[['lowBalance','Low-balance warnings'],['bills','Upcoming bill alerts'],['budgets','Budget threshold alerts'],['subscriptions','Subscription reminders'],['weeklyDigest','Weekly financial digest']].map(([key, label]) => <label key={key} className="flex items-center justify-between rounded-xl border p-3 text-sm"><span>{label}</span><Switch checked={prefs[key]} onCheckedChange={value => setPrefs({ ...prefs, [key]: value })}/></label>)}<div className="pt-2"><Label>Low-balance threshold</Label><Input className="mt-1" type="number" value={prefs.lowBalanceThreshold} onChange={e => setPrefs({ ...prefs, lowBalanceThreshold: Number(e.target.value) })}/></div><Button className="mt-2 w-full" onClick={() => savePrefs.mutate()}>Save preferences</Button></div></div><div className="space-y-3">{notificationData.data?.items?.map((item: any) => <div key={item.id} className={`glass-card rounded-xl p-4 ${!item.readAt ? 'border-primary/30' : ''}`}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-muted-foreground">{item.message}</p></div>{!item.readAt && <span className="mt-1 h-2 w-2 rounded-full bg-primary"/>}</div><p className="mt-2 text-[11px] text-muted-foreground">{new Date(item.createdAt).toLocaleString()}</p></div>)}{!notificationData.data?.items?.length && <div className="glass-card rounded-2xl p-12 text-center text-sm text-muted-foreground">No notifications yet. Important financial events will appear here.</div>}</div></TabsContent>
    </Tabs></div>;
}
