import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, BadgeDollarSign, Landmark, ShieldCheck, TrendingUp } from 'lucide-react';
import { customFetch } from '@workspace/api-client-react/custom-fetch';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Progress } from '@/components/ui/progress';
import PagePurpose from '@/components/PagePurpose';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { formatCurrency } from '@/lib/utils';

export default function Wealth() {
  const client = useQueryClient(); const [months, setMonths] = useState('6');
  const net = useQuery({ queryKey: ['net-worth'], queryFn: () => customFetch<any>('/api/net-worth', { responseType: 'json' }) });
  const emergency = useQuery({ queryKey: ['emergency', months], queryFn: () => customFetch<any>(`/api/emergency-fund?months=${months}`, { responseType: 'json' }) });
  const credit = useQuery({ queryKey: ['credit'], queryFn: () => customFetch<any[]>('/api/credit', { responseType: 'json' }) });
  const investments = useQuery({ queryKey: ['investments'], queryFn: () => customFetch<any>('/api/investments', { responseType: 'json' }) });
  const [creditForm, setCreditForm] = useState({ score: '', totalLimit: '', statementBalance: '' }); const [position, setPosition] = useState({ symbol: '', name: '', assetClass: 'Stocks', quantity: '', currentPrice: '', costBasis: '' });
  const saveCredit = useMutation({ mutationFn: () => customFetch('/api/credit', { method: 'POST', responseType: 'json', body: JSON.stringify(creditForm) }), onSuccess: () => { client.invalidateQueries({ queryKey: ['credit'] }); setCreditForm({ score: '', totalLimit: '', statementBalance: '' }); } });
  const savePosition = useMutation({ mutationFn: () => customFetch('/api/investments', { method: 'POST', responseType: 'json', body: JSON.stringify(position) }), onSuccess: () => { client.invalidateQueries({ queryKey: ['investments'] }); setPosition({ symbol: '', name: '', assetClass: 'Stocks', quantity: '', currentPrice: '', costBasis: '' }); } });
  const latest = credit.data?.[0]; const utilization = Number(latest?.utilization ?? 0);
  return <div className="space-y-7 pb-12"><header><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Wealth</p><h1 className="mt-1 text-3xl font-bold">Financial health</h1><p className="mt-1 text-sm text-muted-foreground">Track the full balance sheet, safety runway, credit health, and asset allocation.</p></header><PagePurpose items={[{ icon: Landmark, title: 'Understand net worth', description: 'View assets and liabilities as one balance sheet.' }, { icon: ShieldCheck, title: 'Measure your safety net', description: 'Track how many months your reserves can cover.' }, { icon: Activity, title: 'Monitor credit health', description: 'Keep utilization and obligations in a safer range.' }, { icon: TrendingUp, title: 'Review allocation', description: 'See whether investments match your priorities.' }]} />
    <div className="grid gap-4 sm:grid-cols-3"><Metric icon={Landmark} label="Net worth" value={formatCurrency(net.data?.netWorth ?? 0)}/><Metric icon={TrendingUp} label="Investments" value={formatCurrency(investments.data?.total ?? 0)}/><Metric icon={ShieldCheck} label="Emergency coverage" value={`${Number(emergency.data?.monthsCovered ?? 0).toFixed(1)} months`}/></div>
    <Tabs defaultValue="net-worth"><TabsList className="grid h-auto grid-cols-2 sm:grid-cols-4"><TabsTrigger value="net-worth">Net worth</TabsTrigger><TabsTrigger value="emergency">Emergency fund</TabsTrigger><TabsTrigger value="credit">Credit</TabsTrigger><TabsTrigger value="investments">Investments</TabsTrigger></TabsList>
      <TabsContent value="net-worth" className="mt-5 space-y-4"><div className="glass-card rounded-2xl p-6"><div className="flex items-end justify-between"><div><p className="text-sm text-muted-foreground">Next milestone</p><p className="font-mono text-2xl font-bold">{formatCurrency(net.data?.milestone?.next ?? 0)}</p></div><p className="text-sm text-muted-foreground">{formatCurrency(net.data?.milestone?.remaining ?? 0)} remaining</p></div><Progress value={net.data?.milestone?.progress ?? 0} className="mt-4"/></div><div className="grid gap-3 sm:grid-cols-2">{net.data?.accounts?.map((item: any) => <div key={item.id} className="glass-card flex items-center justify-between rounded-xl p-4"><div><p className="font-medium">{item.name}</p><p className="text-xs capitalize text-muted-foreground">{item.type.replace('_', ' ')}</p></div><p className="font-mono font-semibold">{formatCurrency(item.balance)}</p></div>)}</div></TabsContent>
      <TabsContent value="emergency" className="mt-5"><div className="glass-card rounded-2xl p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-lg font-semibold">Readiness target</h2><p className="text-sm text-muted-foreground">Based on the trailing three-month expense average.</p></div><div><Label htmlFor="months">Target months</Label><Input id="months" className="mt-1 w-28" type="number" min="1" max="12" value={months} onChange={e => setMonths(e.target.value)}/></div></div><Progress className="mt-6" value={Math.min(100, Number(emergency.data?.monthsCovered ?? 0) / Number(months) * 100)}/><div className="mt-6 grid gap-3 sm:grid-cols-3"><Small label="Liquid funds" value={formatCurrency(emergency.data?.liquid ?? 0)}/><Small label="Target" value={formatCurrency(emergency.data?.target ?? 0)}/><Small label="Remaining gap" value={formatCurrency(emergency.data?.gap ?? 0)}/></div><p className="mt-4 text-xs text-muted-foreground">{emergency.data?.explanation}</p></div></TabsContent>
      <TabsContent value="credit" className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="glass-card rounded-2xl p-6"><Activity className="h-6 w-6 text-primary"/><p className="mt-5 text-sm text-muted-foreground">Latest score</p><p className="font-mono text-4xl font-bold">{latest?.score ?? '—'}</p><p className="mt-4 text-sm">Utilization <span className={utilization > 30 ? 'text-red-400' : 'text-primary'}>{utilization.toFixed(1)}%</span></p><Progress className="mt-2" value={Math.min(100, utilization)}/><p className="mt-3 text-xs text-muted-foreground">Aim below 30%; below 10% is typically strongest. Scores are manually tracked until a bureau provider is connected.</p></div><form className="glass-card grid gap-4 rounded-2xl p-6 sm:grid-cols-3" onSubmit={e => { e.preventDefault(); saveCredit.mutate(); }}>{(['score','totalLimit','statementBalance'] as const).map(key => <div key={key}><Label className="capitalize">{key.replace(/([A-Z])/g, ' $1')}</Label><Input className="mt-1" type="number" value={creditForm[key]} onChange={e => setCreditForm({ ...creditForm, [key]: e.target.value })}/></div>)}<Button className="sm:col-span-3" disabled={saveCredit.isPending}>Save credit snapshot</Button></form></TabsContent>
      <TabsContent value="investments" className="mt-5 space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{investments.data?.positions?.map((item: any) => <div key={item.id} className="glass-card rounded-2xl p-5"><div className="flex justify-between"><BadgeDollarSign className="h-5 w-5 text-primary"/><span className="text-xs text-muted-foreground">{item.assetClass}</span></div><p className="mt-4 font-semibold">{item.symbol} · {item.name}</p><p className="mt-1 font-mono text-xl font-bold">{formatCurrency(item.value)}</p><p className={`text-xs ${item.gain >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>{item.gain >= 0 ? '+' : ''}{formatCurrency(item.gain)} total gain</p></div>)}</div><form className="glass-card grid gap-3 rounded-2xl p-5 sm:grid-cols-3" onSubmit={e => { e.preventDefault(); savePosition.mutate(); }}>{Object.entries(position).map(([key, value]) => <div key={key}><Label className="capitalize">{key.replace(/([A-Z])/g, ' $1')}</Label><Input className="mt-1" type={['quantity','currentPrice','costBasis'].includes(key) ? 'number' : 'text'} value={value} onChange={e => setPosition({ ...position, [key]: e.target.value })}/></div>)}<Button className="sm:col-span-3" disabled={savePosition.isPending}>Add position</Button></form></TabsContent>
    </Tabs></div>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof Landmark; label: string; value: string }) { return <div className="glass-card rounded-2xl p-5"><Icon className="h-5 w-5 text-primary"/><p className="mt-4 text-xs text-muted-foreground">{label}</p><p className="mt-1 font-mono text-2xl font-bold">{value}</p></div>; }
function Small({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-muted/40 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-mono font-semibold">{value}</p></div>; }
